name: ripplelib
version: 0.1.1
author: Steven Roose <stevenroose@gmail.com>
description: The Ripple library for Dart.
homepage: https://github.com/stevenroose/ripple-lib-dart
dependencies:
  asn1lib: '>=0.4.1'
  bignum: '>=0.1.0'
  browser: any
  pointycastle: '>=0.10.0+1'
  collection: any
  cryptoutils: '>=0.2.1'
  crypto: any
  decimal: '>=0.1.3'
  enums: '>=0.2.3'
  events: '>=0.1.0'
  json_object: '>=1.0.19'
  logging: '>=0.11.2 <1.0.0'
  stevenroose: '>=0.1.0'
  websockets: '>=0.1.1'
dev_dependencies:
  test: any