name: ripple-lib
dependencies:
  bignum: any
  browser: any
  cryptoutils: '>=0.1.9'
  crypto: any
  decimal: '>=0.1.2'
  enums: '>=0.2.3'
  events: '>=0.1.0'
  event_emitter: '>=0.2.0'
  json_object:
    git: https://github.com/stevenroose/dartwatch-JsonObject